package com.careerdevs.bankingapp.controllers;

import com.careerdevs.bankingapp.models.AccountModel;
import com.careerdevs.bankingapp.models.UserModel;
import com.careerdevs.bankingapp.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URLs start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @PostMapping("/add")
    public ResponseEntity<UserModel> createAccount(@RequestBody UserModel newUser) {


        UserModel savedUser = userRepository.save(newUser);
        return new ResponseEntity<>(savedUser, HttpStatus.CREATED);
    }

    @GetMapping("/all")
    public ResponseEntity<Iterable<UserModel>> getAllUsers() {
        Iterable<UserModel> allUsers = userRepository.findAll();
        return new ResponseEntity<>(allUsers, HttpStatus.OK);
    }

}

